spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension

spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog

spark.sql.catalogImplementation=hive

spark.hadoop.hive.metastore.uris=thrift://hive-metastore:9083

spark.sql.warehouse.dir=/warehouse